/*
 * Ferris D.
 * 04/11/2018
 */

package Something;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.text.DefaultCaret;


/**
 *
 * @author fedie2562
 */
public class Something extends javax.swing.JFrame {
    // Get resolution for window bounce
    Dimension resolution = Toolkit.getDefaultToolkit().getScreenSize();
    int resX = (int) resolution.getWidth();
    int resY = (int) resolution.getHeight();
    int locX = 0, locY = 0;
    boolean goM = false;
    boolean go = false;
    String output = "";
    int noted1=0, noted2=200, noted3=50;
    int u1=5,u2=5,u3=5,xx=2,yy=2;
    int n1=(int)(Math.random()*5),n2=1,n3=1;
    int moted1=(int)(Math.random()*249+1),moted2=(int)(Math.random()*249+1),moted3=(int)(Math.random()*249+1);
    //
    @Override
    public void setLocation(int i, int i1) {
        super.setLocation(i, i1); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * Creates new form Something
     */
    public Something() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runningToggle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputField = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));
        setForeground(new java.awt.Color(255, 0, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(379, 335));

        runningToggle.setText("Start");
        runningToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runningToggleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Three Arrows", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STUFF");

        jButton1.setText("Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(runningToggle))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(runningToggle)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        jPanel2.setEnabled(false);
        jPanel2.setOpaque(false);

        outputField.setColumns(20);
        outputField.setForeground(new java.awt.Color(100, 0, 0));
        outputField.setRows(5);
        jScrollPane1.setViewportView(outputField);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 312, Short.MAX_VALUE)
                .addComponent(jButton2))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(26, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runningToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runningToggleActionPerformed
        // 
        go = !go;
        AltThread zoom = new AltThread();
        zoom.start();
        if(go){
            System.out.println("on");
            runningToggle.setText("Stop");
        }
        else{
            System.out.println("off");
            runningToggle.setText("Start");
        }
    }//GEN-LAST:event_runningToggleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 
        go = false;
        jPanel1.setVisible(go);
        jPanel2.setVisible(true);
        goM = !goM;
        System.out.println(moted1+" "+moted2+" "+moted3);
        MThread mTred = new MThread();
        mTred.start();
        if(goM){
            System.out.println("on");
            runningToggle.setText("Stop");
        }
        else{
            System.out.println("off");
            runningToggle.setText("Start");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //
        goM = false;
        go = false;
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        runningToggle.setText("Start");
    }//GEN-LAST:event_jButton2ActionPerformed
    public class MThread extends Thread{
        @Override
        public void run(){
            output = "";
            DefaultCaret caret = (DefaultCaret)outputField.getCaret();
            caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
            int counter = 0;
            while(goM){
                n1 *= (moted1 > 249 && n1 > 0) || (n1 < 0 && moted1 < 5) ? -1 : 1;
                n2 *= (moted2 > 249 && n2 > 0) || (n2 < 0 && moted2 < 5) ? -1 : 1;
                n3 *= (moted3 > 249 && n3 > 0) || (n3 < 0 && moted3 < 5) ? -1 : 1;
                moted1 += n1;
                moted2 += n2;
                moted3 += n3;
                Color nn = new Color(moted1, moted2, moted3);
                outputField.setForeground(nn);
                if(counter < 47){
                    counter++;
                }else if(counter >= 47){
                    counter = 0;
                    output += "\n";
                }
                output += "" + (int) (Math.random() * 10);
                System.out.println(moted1+ " " + moted2 + " " + moted3);
                outputField.setText(output);
                sleeper(10);
            }
        }
    }
    public class AltThread extends Thread{
        @Override
        public void run(){
            while(go)
            {
                u1 *= (noted1 > 249 && u1 > 0) || (u1 < 0 && noted1 < 1) ? -1 : 1;
                u2 *= (noted2 > 249 && u2 > 0) || (u2 < 0 && noted2 < 1) ? -1 : 1;
                u3 *= (noted3 > 249 && u3 > 0) || (u3 < 0 && noted3 < 1) ? -1 : 1;
                xx *= (locX > (resX - 379) && xx > 0) || (xx < 0 && locX < 0) ? -1 : 1;
                yy *= (locY > (resY - 354) && yy > 0) || (yy < 0 && locY < 0) ? -1 : 1;
                locX += xx;
                locY += yy;
                noted1 += u1;
                noted2 += u2;
                noted3 += u3;
                Color cc = new Color(noted1, noted2, noted3);
                Color vv = new Color(noted1, noted3, noted3);
                int rando = (int) (Math.random() * 9999999 + 1000);
                jLabel1.setText(rando+rando+"");
                jLabel1.setForeground(vv);
                jPanel1.setBackground(cc);
                setLocation(locX, locY);
                sleeper(50);
            }
            
        }
    }
    public void sleeper(int millis){
        try {
            AltThread.sleep(millis);
        }catch(InterruptedException ex){}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Something.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Something().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputField;
    private javax.swing.JToggleButton runningToggle;
    // End of variables declaration//GEN-END:variables
}
